config/routes.rb
HrSystem::Application.routes.draw do
  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  resources :reports do
    get :summary, on: :collection
  end
  resources :report_categories
  resources :vacation_types
  
  resources :stickies
  resources :users do
    get :get_team, on: :collection
    get :get_all_user, on: :collection
    get :profile, on: :member
    patch :update_profile, on: :member
    post :update_profile, on: :member
    post :update_user_role, on: :collection
    get :organizations, on: :collection
  end
  
  resources :groups do
    resources :teams
  end

  resources :project_users do
    resources :project_user_roles
  end

  resources :projects do
    resources :costs
    resources :project_users do
      get :member_list, on: :collection
      post :update_roles, on: :collection
    end
    get :gantt, on: :collection
    get :gantt_list, on: :collection
    get :export_excel, on: :collection
    post :assign_members, on: :collection
  end
  resources :project_users

  resources :payslips do
    get :download, on: :member
    post :send_payslip, on: :collection
  end

  resources :feedbacks do
    get :fixed, on: :member
  end

  resources :checkpoint_periods
  resources :questions
  resources :question_types do
    post :add_questions, on: :collection
    resources :question_type_relations
  end

  resources :checkpoints do
    get :review, on: :member
    get :ranking, on: :collection
  end

  resources :pickup_lists do
    post :assign_members, on: :collection
    resources :pickup_list_users, only: [:index, :destroy]
  end

  root to: "users#index"

end

app/models/checkpoint.rb
class Checkpoint < Base
  belongs_to :checkpoint_period, foreign_key: :checkpoint_period_id

  validates :user_id, uniqueness: {scope: :checkpoint_period_id}, presence: true

  scope :by_periods, ->(period_id) { where("checkpoints.checkpoint_period_id = ?", period_id) unless period_id.nil? }
  scope :by_approve, ->(approve_id) { where("checkpoints.approve_id = ?", approve_id) unless approve_id.nil? }
  scope :by_reviewer, ->(review_id) { where("checkpoints.reviewer_id = ? and checkpoints.user_id != checkpoints.reviewer_id", review_id) unless review_id.nil? }
  scope :approve, -> {where state: "approve"}
  scope :by_rank, ->rank { where("checkpoints.ranking = ?", rank) unless rank.nil? }

  has_many :checkpoint_answers, dependent: :destroy
  belongs_to :checkpoint_period
  belongs_to :user
  accepts_nested_attributes_for :checkpoint_answers, allow_destroy: true

  state_machine :state, initial: :waitting do
    event :reviewing do
      transition :waitting => :reviewing
    end

    event :reviewed do
      transition [:waitting, :reviewing] => :reviewed
    end

    event :approve do
      transition :reviewed => :approve
    end

    state :waitting
    state :reviewing
    state :reviewed
    state :approve
  end

  def build_checkpoint_answers
    if self.checkpoint_answers.empty?
      self.checkpoint_period.questions.by_type(self.user.position).
        each { |question| self.checkpoint_answers.build(question_id: question.id) }
    end
  end

  def build_checkpoint_comments(user_id)
    self.checkpoint_answers.each { |answer| answer.user_answer_comments.build(user_id: user_id) }
  end

  def new_checkpoint?
    waitting?
  end

  def reviewable?
    reviewing?
  end

  def approveable?
    reviewed?
  end
end

app/models/team.rb
class Team < Base
  #attr_accessible :name, :group_id
  scope :in_groups, ->(group_ids) { where("group_id in (?)", group_ids) unless group_ids.nil? }

  belongs_to :group
  has_many :users
end

app/controllers/checkpoints_controller.rb
class CheckpointsController < BaseController
  before_filter :check_answers, only: [:edit]
  before_filter :build_comments, only: [:review]
  
  def index
    if current_user.is_leader?
      @review_checkpoints = Checkpoint.by_reviewer(current_user.id)
      @review_checkpoints = @review_checkpoints.paginate(page: params[:page],per_page: params[:per_page])
    end
    respond_to do |format|
      format.html
    end
  end

  def new
    params[:period] ||= CheckpointPeriod.first.try(:id)
    checkpoints = Checkpoint.by_periods(params[:period]) unless params[:period].nil?
    # Return users not create with periods
    if checkpoints.blank?
      @users = params[:period].nil? ? [] : User.reporters
    else
      @users = User.reporters.not_in(checkpoints.map(&:user_id))
    end
  end

  def edit
    respond_to do |format|
      format.html
    end
  end

  def review
    respond_to do |format|
      format.html
    end
  end

  def create
    # Create multiple checkpoint with each user_id
    if params[:user_ids].present?
      Checkpoint.create(params[:user_ids].map { |user_id| {user_id: user_id} }) do |checkpoint|
        checkpoint.checkpoint_period_id = params[:period]
        checkpoint.reviewer_id = params[:review]
        checkpoint.approve_id = params[:approve]
      end
      notice = t(:create_success, scope: [:views, :messages], model: model_name)
    else
      notice = t(:choose_member, scope: [:views, :messages])
    end
    respond_to do |format|
      format.html { redirect_to new_checkpoint_path(period: params[:period]), notice: notice }
    end
  end
 
  def update
    respond_to do |format|
      if @checkpoint.update_attributes(model_params)
        format.html { redirect_to @checkpoint, notice: t(:update_success, scope: [:views, :messages], model: model_name) }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @checkpoint.destroy
        format.html { redirect_to action: :index }
      else
        format { redirect_to action: :index, notice: t(:delete_failed, scope: [:views, :messages]) }
      end
    end
  end

  def ranking
    @q = Checkpoint.search params[:q]
    @checkpoints = @q.result.approve
    respond_to do |format|
      format.html
    end
  end

private
  def check_answers
    @checkpoint.build_checkpoint_answers
  end

  def ordering(search)
    if current_user.is_staff?
      current_user.checkpoints
    elsif current_user.is_leader?
      current_user.checkpoints
    elsif current_user.is_manager?
      current_user.is_hr? ? Checkpoint.all : Checkpoint.by_approve(current_user.id).order("id DESC")
    end
  end

  def build_comments
    @checkpoint = Checkpoint.find params[:id]
    if current_user.user_answer_comments.by_checkpoint(@checkpoint.checkpoint_answers.ids).empty?
      @checkpoint.build_checkpoint_comments(current_user.id)
    end
  end

  def model_params
    params.require(:checkpoint).permit(:checkpoint_period_id, :state_event, :ranking,
                                    checkpoint_answers_attributes: [:id, :checkpoint_question_id ,:content, :point, :_destroy, 
                                    user_answer_comments_attributes: [:id, :comment , :user_id, :_destroy]]) if params[:checkpoint]
  end
end

app/helpers/checkpoints_helper.rb
module CheckpointsHelper
end

app/views/checkpoints/_answer_fields.html.erb
<%= f.fields_for :checkpoint_answers, checkpoint_answer do |checkpoint_answers| %>
  <tr>
    <td colspan = 2 style = "padding-left:5%;" ><%= checkpoint_answer.question.content %></td>
  </tr>
  <tr>
    <td class = "labels">
      <%= checkpoint_answers.text_area :content, style: "width: 50%" %>
    </td>
  </tr>
  <tr>
    <td class = "labels">
      <%= checkpoint_answers.text_field :point %>points
      <%= checkpoint_answers.hidden_field :question_id %>
    </td>
  </tr>
<% end %>

app/views/checkpoints/_answer_review_fields.html.erb
<%= f.fields_for :checkpoint_answers, checkpoint_answer do |answer| %>
  <tr>
    <td colspan = 2 style = "padding-left:5%;" ><%= checkpoint_answer.checkpoint_question.content %></td>
  </tr>
  <tr>
    <td class = "labels">
      <%= checkpoint_answer.content %>
    </td>
  </tr>
  <tr>
    <td class = "labels">
      <%= checkpoint_answer.point %>/<%= checkpoint_answer.checkpoint_question.max_point %>
    </td>
  </tr>
  <% checkpoint_answer.user_answer_comments && checkpoint_answer.user_answer_comments.each_with_index do |user_answer_comment, i| %>
     <%= render "comment_fields", {user_answer_comment: user_answer_comment, f: answer, i: i } %>
  <% end %>
<% end %>

app/views/checkpoints/_comment_fields.html.erb
<%= f.fields_for :user_answer_comments, user_answer_comment do |comment| %>
  <tr>
    <% if current_user.id == user_answer_comment.user_id %>
      <td class = "labels">
        <%= comment.text_area :comment, style: "width: 50%" %>
        <%= comment.hidden_field :user_id %>
      </td>
    <% else %>
      <td class = "labels">
        Comment by <%= user_answer_comment.user.display_name %>: <%= user_answer_comment.comment %>
      </td>
    <% end %>
  </tr>
<% end %>

app/views/checkpoints/_form.html.erb
<%= form_tag checkpoints_path, id: "checkpoint_periods" do %>
  <div class="lst_member_bottom">
    <table>
      <tr>
        <th colspan="7" style="text-align: center; font-size: 15px; font-weight: bold;"><%= model.human_attribute_name :period %>
          <%= select_tag :period, options_for_select(CheckpointPeriod.all.map { |period| [period.toString, period.id] }, params[:period]) %>
          <%= model.human_attribute_name :review %>
          <%= select_tag :review, options_for_select(User.find_leaders.map { |leader| [leader.display_name, leader.team_id] }), include_blank: true, id: "leader_select", class: "leaders" %>
          <%= model.human_attribute_name :approve %>
          <%= select_tag :approve, options_for_select(User.find_managers.map { |manager| [manager.display_name, manager.id] }) %>
          <label for="name_search">Name</label>
          <input id="name_search" type="text width: 130px" name="name_search" >
        </th>
      </tr>
      <tr>
        <td class="all_member">
          <% @users.each_with_index do |user, index| %>
            <div style="display: inline-block; width: 120px;" class= "member_item" data-team = "<%= user.team_id %>">
              <%= link_to image_tag(user.avatar_url, class: "member_avatar #{ 'border_blue' if params[:member_id].to_i == user.id }",
                    alt: "No image"), url_for(action: :index, member_id: user.id), data: user.display_name %><br>
              <div class = "user_name" data-id = "<%= user.display_name.downcase %>">
                <%= link_to user.display_name, profile_user_path(user.id) %>
              </div>
              <br>
              <%= check_box_tag "user_ids[]", user.id %>
            </div>
         <% end %>
        </td>
      </tr>
    </table>
    <%= submit_tag t(:button_checkpoints, scope: [:views, :labels]), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/checkpoints/_questions.html.erb
<%= form_for @checkpoint, url: {action: @checkpoint.new_record? ? :create : :update} do |f| %>

  <%= render partial: "errors", locals: {object: @checkpoint} %>

  <table class="survey">
    <% parent_id = 0 %>
    <% count = 1 %>
    <% @checkpoint.checkpoint_answers && @checkpoint.checkpoint_answers.each_with_index do |checkpoint_answer, i| %>
      <% if checkpoint_answer.question.question_types.present? && 
        parent_id != checkpoint_answer.question.question_types.try(:first).id %>
        <tr>
          <td colspan = 2 style = "padding-left:2%;" ><label><%= count %>.
          <%= checkpoint_answer.question.question_types.try(:first).name %></label></td>
        </tr>
        <% parent_id = checkpoint_answer.question.question_types.try(:first).id %>
        <% count += 1 %>
      <% end %>

      <%= render "answer_fields", {checkpoint_answer: checkpoint_answer, f: f, i: count } %>

    <% end %>
  </table>

  <div class="form-actions" style = "background-color: #FFFFFF;">
    <% if @checkpoint.waitting? && current_user.is_leader? %>
      <%= f.button t(:button_finish, scope: [:views, :labels]), class: "btn btn-primary", 
        name: "#{model_name.underscore}[state_event]", value: "reviewed" %>
    <% else %>
      <%= f.button t(:button_finish, scope: [:views, :labels]), class: "btn btn-primary", 
        name: "#{model_name.underscore}[state_event]", value: "reviewing" %>
    <% end %>
  </div>
<% end %>

app/views/checkpoints/_search_form.html.erb
<div>
  <table class="formTbl contents">
    <tbody>
      <tr>
        <th width = "20%"><%= f.label :checkpoint_period_id %></th>
        <td><%= f.select :checkpoint_period_id_eq, options_for_select(CheckpointPeriod.all.map{|x| [x.name,x.id]}) %></td>
      </tr>
      <tr>
        <th width = "20%"><%= f.label :name %></th>
        <td><%= f.text_field :user_display_name_cont %></td>
      </tr>
      <tr>
        <th><%= f.label :ranking %></th>
          <td>
            <% Settings.users.ranking.each_with_index do |rank, index| %>
              <%= f.radio_button :ranking_eq, rank, style: "display: inline-block;", id: "ranking#{index}" %>
              <label for="<%= 'ranking' + index.to_s %>"><%= rank %></label>
            <% end %>
          </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/checkpoints/_show_fields.html.erb
<%= f.fields_for :checkpoint_answers, checkpoint_answer do |answer| %>
  <tr>
    <td colspan = 2 style = "padding-left:5%;" ><%= checkpoint_answer.checkpoint_question.content %></td>
  </tr>
  <tr>
    <td class = "labels">
      <%= checkpoint_answer.content %>
    </td>
  </tr>
  <tr>
    <td class = "labels">
      <%= checkpoint_answer.point %>/<%= checkpoint_answer.checkpoint_question.max_point %>
    </td>
  </tr>
<% end %>

app/views/checkpoints/edit.html.erb
<selection id="<%= model_name.underscore %>_edit">
  <%= render "questions" %>
</selection>

app/views/checkpoints/index.html.erb
<selection id="checkpoints_index">
  <% if current_user.is_hr? %>
    <div class="link" style="margin-bottom: 15px;">
      <a href="<%= url_for(action: :new) %>" class="link-a">
        <i class="icon_add icon"></i><span><%= t(:button_new, scope: [:views, :labels]) %></span>
      </a>
    </div>
  <% end %>

  <%= render partial: "search" unless current_user.is_hr? %>

  <table class="itemList" style = "background-color: #FFFFFF;">
    <thead>
      <tr>
        <th width = "10%"><%= model.human_attribute_name :period %></th>
        <th><%= model.human_attribute_name :name %></th>
        <th><%= model.human_attribute_name :rank %></th>
        <th width = "20%"></th>
      </tr>
    </thead>
    
    <% @checkpoints.each do |checkpoint| %>
      <tr>
        <td><%= checkpoint.checkpoint_period.name %></td>
        <td><%= checkpoint.user.display_name %></td>
        <td><%= checkpoint.ranking %></td>
        <td>
          <% if current_user.is_hr? %>
            <%= link_to t(:button_delete, scope: [:views, :labels]), url_for(action: :destroy, id: checkpoint.id),
                  confirm: "Do you want to delete it ?", method: :delete, class: "btn btn-mini btn-danger" %>
          <% else %>
              <%= link_to_if( checkpoint.new_checkpoint? && checkpoint.user.id == current_user.id, t(:button_edit, scope: [:views, :labels]), url_for(action: :edit, id: checkpoint.id), class: "btn btn-primary btn-mini") {} %>
              <%= link_to_if(checkpoint.reviewable? && current_user.is_leader?, t(:button_review, scope: [:views, :labels]), url_for(action: :review, id: checkpoint.id), class: "btn btn-success btn-mini") {} %>
              <%= link_to_if(checkpoint.approveable? && current_user.is_manager?, t(:button_review, scope: [:views, :labels]), url_for(action: :review, id: checkpoint.id), class: "btn btn-success btn-mini") {} %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <div class="pagination">
    <div class="paginate-box no_print"><%= will_paginate @checkpoints %></div>
  </div>

  <% if @review_checkpoints.present? %>
    <table class="table table-bordered" style = "background-color: #FFFFFF;">
      <thead>
        <tr>
          <th width = "10%"><%= model.human_attribute_name :period %></th>
          <th><%= model.human_attribute_name :name %></th>
          <th><%= model.human_attribute_name :rank %></th>
          <th width = "20%"></th>
        </tr>
      </thead>
      <% @review_checkpoints.each do |checkpoint| %>
        <tr>
          <td><%= checkpoint.checkpoint_period.name %></td>
          <td><%= checkpoint.user.display_name %></td>
          <td><%= checkpoint.ranking %></td>
          <td>
            <%= link_to_if( checkpoint.new_checkpoint? && checkpoint.user.id == current_user.id, t(:button_edit, scope: [:views, :labels]), url_for(action: :edit, id: checkpoint.id), class: "btn btn-primary btn-mini") {} %>
            <%= link_to_if(checkpoint.reviewable? && current_user.is_leader?, t(:button_review, scope: [:views, :labels]), url_for(action: :review, id: checkpoint.id), class: "btn btn-success btn-mini") {} %>
            <%= link_to_if(checkpoint.approveable? && current_user.is_manager?, t(:button_review, scope: [:views, :labels]), url_for(action: :review, id: checkpoint.id), class: "btn btn-success btn-mini") {} %>
          </td>
        </tr>
      <% end %>
    </table>
    <div class="pagination">
      <div class="paginate-box no_print"><%= will_paginate @review_checkpoints %></div>
    </div>
  <% end %>
</selection>

app/views/checkpoints/ranking.html.erb
<%= search_form_for @q, url: ranking_checkpoints_path do |f| %>
  <div class="center">
    <div class="span9 search-col">
      <%= f.collection_select :checkpoint_period_id_eq, CheckpointPeriod.all, :id, :name, include_blank: t(:all_periods, scope: [:views, :rankings]) %>
      <%= f.submit t(:button_search, scope: [:views, :labels]), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<div class="lst_member_bottom">
  <table>
    <tr>
      <th>Rank</th>
      <th>Members</th>
    </tr>
    <% Settings.users.ranking.each do |rank| %>
      <tr>
        <th><%= rank %></th>
        <td>
          <% @checkpoints.by_rank("#{rank}").try(:each) do |checkpoint| %>
            <div style="display: inline-block" class= "member_item">
              <%= link_to image_tag(checkpoint.user.avatar_url, class: "member_avatar",
                alt: "No image"), url_for(action: :index, member_id: checkpoint.user.id), data: checkpoint.user.display_name %><br>
              <%= link_to checkpoint.user.display_name, profile_user_path(checkpoint.user.id) %>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/checkpoints/review.html.erb
<selection id="<%= model_name.underscore %>_review">
  <%= form_for @checkpoint, url: {action: @checkpoint.new_record? ? :create : :update} do |f| %>

    <%= render partial: "errors", locals: {object: @checkpoint} %>

    <table class="survey">
      <% parent_id = 0 %>
      <% count = 1 %>
      <% @checkpoint.checkpoint_answers && @checkpoint.checkpoint_answers.each_with_index do |checkpoint_answer, i| %>
        <% if checkpoint_answer.checkpoint_question.parent.present? &&
          parent_id != checkpoint_answer.checkpoint_question.parent.id %>
          <tr>
            <td colspan = 2 style = "padding-left:2%;" ><label><%= count %>.
            <%= checkpoint_answer.checkpoint_question.parent.content %></label></td>
          </tr>
          <% parent_id = checkpoint_answer.checkpoint_question.parent.id %>
          <% count += 1 %>
        <% end %>
        <%= render "answer_review_fields", {checkpoint_answer: checkpoint_answer, f: f, i: i } %>
      <% end %>
    </table>

    <% if current_user.is_manager? && current_user.id == @checkpoint.approve_id  %>
      <table class="ranking">
        <tr>
          <th><%= f.label :ranking %></th>
          <td>
            <% Settings.users.ranking.each_with_index do |rank, index| %>
              <%= f.radio_button :ranking, rank, style: "display: inline-block;", id: "ranking#{index}" %>
              <label for="<%= 'ranking' + index.to_s %>"><%= rank %></label>
            <% end %>
          </td>
        </tr>
      </table>
      <div class="form-actions" style = "background-color: #FFFFFF;">
        <% if @checkpoint.approveable?  %>
          <%= f.button t(:button_finish, scope: [:views, :labels]), class: "btn btn-primary", 
            name: "#{model_name.underscore}[state_event]", value: "approve" %>
        <% end %>
      </div>
    <% else %>
      <div class="form-actions" style = "background-color: #FFFFFF;">
        <%= f.button t(:button_finish, scope: [:views, :labels]), class: "btn btn-primary",
          name: "#{model_name.underscore}[state_event]", value: "reviewed" %>
      </div>
    <% end %>
    
  <% end %>
</selection>

app/views/checkpoints/show.html.erb
<selection id="<%= model_name.underscore %>_review">
  <%= form_for @checkpoint do |f| %>

    <%= render partial: "errors", locals: {object: @checkpoint} %>

    <table class="survey">
      <% parent_id = 0 %>
      <% count = 1 %>
      <% @checkpoint.checkpoint_answers && @checkpoint.checkpoint_answers.each_with_index do |checkpoint_answer, i| %>
        <% if checkpoint_answer.checkpoint_question.parent.present? &&
          parent_id != checkpoint_answer.checkpoint_question.parent.id %>
          <tr>
            <td colspan = 2 style = "padding-left:2%;" ><label><%= count %>.
                <%= checkpoint_answer.checkpoint_question.parent.content %></label></td>
          </tr>
          <% parent_id = checkpoint_answer.checkpoint_question.parent.id %>
          <% count += 1 %>
        <% end %>
        <%= render "answer_review_fields", {checkpoint_answer: checkpoint_answer, f: f, i: i } %>
      <% end %>
      <table class="ranking">
        <tr>
          <th width ="10%"><%= f.label :ranking %></th>
          <td>
            <%= @checkpoint.ranking %>
          </td>
        </tr>
      </table>
    </table>
  <% end %>
</selection>