config/routes.rb
HrSystem::Application.routes.draw do
  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  resources :reports do
    get :summary, on: :collection
  end
  resources :report_categories
  resources :vacation_types
  
  resources :stickies
  resources :users do
    get :get_team, on: :collection
    get :get_all_user, on: :collection
    get :profile, on: :member
    patch :update_profile, on: :member
    post :update_profile, on: :member
    post :update_user_role, on: :collection
    get :organizations, on: :collection
  end
  
  resources :groups do
    resources :teams
  end

  resources :project_users do
    resources :project_user_roles
  end

  resources :projects do
    resources :costs
    resources :project_users do
      get :member_list, on: :collection
      post :update_roles, on: :collection
    end
    get :gantt, on: :collection
    get :gantt_list, on: :collection
    get :export_excel, on: :collection
    post :assign_members, on: :collection
  end
  resources :project_users

  resources :payslips do
    get :download, on: :member
    post :send_payslip, on: :collection
  end

  resources :feedbacks do
    get :fixed, on: :member
  end

  resources :checkpoint_periods
  resources :questions
  resources :question_types do
    post :add_questions, on: :collection
    resources :question_type_relations
  end

  resources :checkpoints do
    get :review, on: :member
    get :ranking, on: :collection
  end

  resources :pickup_lists do
    post :assign_members, on: :collection
    resources :pickup_list_users, only: [:index, :destroy]
  end

  root to: "users#index"

end

app/models/project.rb
class Project < Base

  validates :url, format: { with: /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix }, allow_nil: true, allow_blank: true
  after_create :set_manager
  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users
  has_many :costs, dependent: :destroy
  scope :get_project_by_state, ->(state) { where("projects.state = ?", state) }
  scope :project_with_user, ->(user_id) { joins(:project_users).where("project_users.user_id = ?", user_id) unless user_id.nil? }
  scope :current_projects, ->(user_id) { project_with_user(user_id).get_project_by_state("actived") }
  scope :last_projects, ->(user_id) { project_with_user(user_id).get_project_by_state("finished") }
  state_machine :state, initial: :prepared do
    event :prepare do
      transition :prepared => :prepared
    end

    event :activate do
      transition [:prepared, :actived] => :actived
    end

    event :finish do
      transition :actived => :finished
    end

    state :prepared
    state :actived
    state :finished
  end

  accepts_nested_attributes_for :project_users, allow_destroy: true, reject_if: :all_blank

  def preparable?
    prepared?
  end

  def activatable?
    prepared? || actived?
  end

  def finishable?
    actived?
  end

  def editable?
    !finished?
  end

  def deletable?
    prepared?
  end

  def set_manager
    params = {project_users_attributes: {0 => {join_date: start_date, due_date: due_date, user_id: create_user_id,
               project_user_roles_attributes: {0 => {project_role_id: 1}}}}}
    update_attributes(params)
  end

  def build_project_user user_id
    self.project_users.build user_id: user_id
  end

private
  class << self
    def updatable_attrs
      [:name, :description, :is_publish, :url, :start_date, :due_date, :end_date, :state_event, :create_user_id,
        project_users_attributes: [:id, :user_id, :project_id, :join_date, :due_date, :_destroy,
        project_user_roles_attributes: [:id, :project_user_id, :project_role_id, :_destroy]]]
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < BaseController

  def index
    respond_to do |format|
      format.html
    end
  end

  def new
    respond_to do |format|
      format.html
    end
  end

  def edit
    respond_to do |format|
      format.html
    end
  end

  def create
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: t(:create_success, scope: [:views, :messages], model: model_name) }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update_attributes(model_params)
        if params[:project][:project_users_attributes]
          format.html { redirect_to url_for(controller: :project_users, action: :index, project_id: @project.id),
            notice: t(:update_success, scope: [:views, :messages], model: model_name) }
        else
          format.html { redirect_to @project, notice: t(:update_success, scope: [:views, :messages], model: model_name) }
        end
      else
        format.html { render action: "new" }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @project.destroy
        format.html { redirect_to action: :index }
      else
        format { redirect_to action: :show }
      end
    end
  end

  def gantt_list
    respond_to do |format|
      format.html
    end
  end


  def gantt
    @list_gantt = User.reporters.map do |user|
      projects = user.project_users.map do |project_user|
        {from: "/Date(#{project_user.join_date.to_time.to_i*1000})/", to: "/Date(#{project_user.convert_date})/" ,
         label: project_user.project.name, customClass: ["ganttRed","ganttGreen","ganttBlue"].sample }
      end
      {:name => user.display_name, values: projects}
    end
    respond_to do |format|
      format.json {render json: @list_gantt}
    end
  end

  def export_excel
    join_dates = ProjectUser.where(user_id: [User.reporters.map(&:id)]).map(&:join_date)
    out_dates = ProjectUser.where(user_id: [User.reporters.map(&:id)]).map(&:convert_date)
    out_dates = out_dates.map{ |out_date| Time.at(out_date / 1000).to_date }
    @gantt_scale = params[:gantt_scale]
    date_ranger = DateRanger.new(join_dates.min, out_dates.max, @gantt_scale)

    @list_users = User.reporters.map do |user|
      projects = user.project_users.map do |project_user|
        join_date = project_user.join_date
        out_date = Time.at(project_user.convert_date / 1000).to_date
        if @gantt_scale == Settings.gantt.scale_type.weeks
          [project_user.project.try(:name),
            [date_ranger.get_week_of_years(join_date), date_ranger.get_month_of_years(join_date), date_ranger.get_year_of_weeks(join_date)],
            [date_ranger.get_week_of_years(out_date), date_ranger.get_month_of_years(out_date), date_ranger.get_year_of_weeks(out_date)]]
        else
          [project_user.project.try(:name), [join_date.day, join_date.month, join_date.year],
            [out_date.day, out_date.month, out_date.year]]
        end
      end
      # Return name of user and list project with process of user
      [user.display_name, projects]
    end
    convert_to_index(@list_users, date_ranger.try(@gantt_scale))
    sort_by_join_date @list_users
    @titles = date_ranger.get_titles_array

    respond_to do |format|
      format.xls { headers["Content-Disposition"] = "attachment; filename=projects_gantt.xls" }
    end
  end

private
  def model_params
    params.require(:project).permit Project.updatable_attrs if params[:project]
  end

  def sort_by_join_date list_users
    list_users.each do |user_project|
      user_project[1].sort! { |x, y| x[1] <=> y[1] }
    end
  end

  def convert_to_index list_users, array_type
    length = array_type.first.length
    list_users.each do |user_project|
      user_project[1].each do |project|
        project[1] = array_type.index(project[1].last(length))
        project[2] = array_type.index(project[2].last(length))
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, url: {action: @project.new_record? ? :create : :update} do |f| %>

  <%= render partial: "errors", locals: {object: @project} %>
  <%= f.hidden_field :create_user_id, value: current_user.id %>
  <table class="formTbl contents">
    <tr>
      <th width="15%"><%= f.label :name %></th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th><%= f.label :description %></th>
      <td><%= f.text_area :description, cols: 100, rows: 5 %></td>
    </tr>
    <tr>
      <th><%= f.label :url %></th>
      <td><%= f.text_field :url %></td>
    </tr>
    <tr>
      <th></th>
      <td><%= f.check_box :is_publish %> <%= f.label :is_publish %></td>
    </tr>
    <tr>
      <th><%= f.label :start_date %></th>
      <td><%= f.text_field :start_date, class: "datepicker icon_calendar_small" %></td>
    </tr>
    <tr>
      <th><%= f.label :due_date %></th>
      <td><%= f.text_field :due_date, class: "datepicker icon_calendar_small" %></td>
    </tr>
    <tr>
      <th><%= f.label :end_date %></th>
      <td><%= f.text_field :end_date, class: "datepicker icon_calendar_small" %></td>
    </tr>
  </table>
  <div class="form-actions">
    <% if @project.preparable? %>
      <%= f.button t(:button_prepare, scope: [:views, :labels]), class: "btn btn-primary" %>
    <% end %>
    <% if @project.activatable? %>
      <%= f.button t(:button_active, scope: [:views, :labels]), class: "btn btn-warning", name: "#{model_name.underscore}[state_event]", value: "activate" %>
    <% end %>
    <% if @project.finishable? %>
      <%= f.button t(:button_finish, scope: [:views, :labels]), class: "btn btn-primary", name: "#{model_name.underscore}[state_event]", value: "finish" %>
    <% end %>
    <% unless @project.new_record? %>
      <%= link_to_if(@project.deletable?, t(:button_delete, scope: [:views, :labels]),
          url_for(action: :destroy, id: @project.id), confirm: t(:delete_confirm, scope: [:views, :messages]),
          method: :delete, class: "btn btn-danger") {} %>
    <% end %>
  </div>
<% end %>

app/views/projects/_search_form.html.erb
<div>
  <table class="formTbl contents">
    <tbody>
      <tr>
        <th><%= f.label :name %></th>
        <td><%= f.text_field :name_cont %></td>
      </tr>
      <tr>
        <th><%= f.label :is_publish %></th>
        <td><%= f.select :is_publish_eq, include_not_select + Settings.select_boolean %></td>
      </tr>
      <tr>
        <th><%= f.label :state %></th>
        <td><%= f.select :state_eq, include_not_select + Settings.project.states %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/export_excel.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <ss:Styles>
    <ss:Style ss:ID="s1">
      <ss:Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
      <ss:Font ss:Bold="1"/>
    </ss:Style>
    <ss:Style ss:ID="s2">
      <ss:Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
    </ss:Style>
    <ss:Style ss:ID="s3">
      <ss:Interior ss:Color="#83caff" ss:Pattern="Solid"/>
      <ss:Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
      <ss:Font ss:Bold="1"/>
    </ss:Style>
  </ss:Styles>
  <Worksheet ss:Name="Sheet1">
    <Table x:FullColumns="1" x:FullRows="1">
      <Column ss:Width="115" /> 
      <!-- DRAW TITLE -->
      <% @titles.each do |title| %>
        <Row>
          <Cell><Data ss:Type="String"></Data></Cell>
          <% title.each do |item| %>
            <% if item[1] > 1 %>
              <Cell ss:MergeAcross="<%= item[1] - 1 %>" ss:StyleID="s1"><Data ss:Type="String"><%= item[0] %></Data></Cell>
            <% else %>
              <Cell ss:StyleID="s1"><Data ss:Type="String"><%= item[0] %></Data></Cell>
            <% end %>
          <% end %>
        </Row>  
      <% end %>

      <% if @gantt_scale == Settings.gantt.scale_type.days %>
        <Row>
          <Cell><Data ss:Type="String"></Data></Cell>
          <% wday = DateTime.new(@titles[0][0][0], Date::MONTHNAMES.index(@titles[1][0][0]), @titles[2][0][0]).wday %>
          <% @titles.last.length.times do |n| %>
            <Cell ss:StyleID="s1"><Data ss:Type="String"><%= Settings.gantt.weekdays[(n + wday) % 7] %></Data></Cell>
          <% end %>
        </Row>
      <% end %>
      <!-- Draw process project with each user -->
      <% @list_users.each do |user| %>
        <Row>
          <Cell><Data ss:Type="String"><%= user[0] %></Data></Cell>
          <% index_in_proj = 0 %>
          <% length = 0 %>
          <% project_name = "" %>

          <% @titles.last.each_with_index do |_, index| %>
            <% user[1].each do |u| %>
              <% if u[1] == index %>
                <% index_in_proj = 1 %>
                <% length = u[2] - u[1] %>
                <% project_name = u[0] %>
              <% elsif (index > u[1] && index <= u[2]) || index > u[2] %>
                <% index_in_proj = -1 %>
              <% else %>
                <% index_in_proj = 0 %>
              <% end %>
              <!-- Draw cell with index -->
              <% case index_in_proj %>
              <% when 0 %>
                <Cell><Data ss:Type="String"></Data></Cell>
              <% when 1 %>
                <% if length > 0 %>
                  <Cell ss:StyleID="s3" ss:MergeAcross="<%= length %>"><Data ss:Type="String" ><%= project_name %></Data></Cell>
                <% else %>
                  <Cell ss:StyleID="s3"><Data ss:Type="String" ><%= project_name %></Data></Cell>
                <% end %>
              <% end %>
              <!-- Break if drew a cell for project -->
              <% break if index <= u[2] %>
            <% end %>
          <% end %>
        </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/projects/gantt_list.html.erb
<script src="http://taitems.github.com/UX-Lab/core/js/prettify.js"></script>
<div class="link">
  <a href="<%= export_excel_projects_path(format: "xls", gantt_scale: params[:gantt_scale]) %>" class="link-a">
    <i class="icon_excel icon"></i><span>Export to excel</span>
  </a>
  <%= select_tag :gantt_scale, options_for_select(Settings.gantt.scale, params[:gantt_scale]) %>
</div>
<div class="gantt"></div>

app/views/projects/index.html.erb
<selection id="projects_index">
  <div class="link">
    <a href="<%= url_for(action: :new) %>" class="link-a">
      <i class="icon_add icon"></i><span><%= t(:button_new, scope: [:views, :labels]) %></span>
    </a>
    <a href="<%= url_for(controller: :projects, action: :gantt_list) %>" class="link-a">
      <i class="icon_chart icon"></i><span><%= t(:button_gantt, scope: [:views, :labels]) %></span>
    </a>
  </div>
  
  <div class = "prepare_pr">
    <h2>Project Prepare</h2>
    <ul class="projects root">
      <% Project.get_project_by_state(Settings.state.prepared).each do |project| %>
        <li class="root">
          <div class="root">
            <%= link_to project.name, url_for(action: :show, id: project.id), class: "project my-project" %>
            <% if project.description.present? %>
              <div class="wiki description">
                <p><%= project.description %></p>
              </div>
            <% end %>
          </div>
        </li>
      <% end %>
    <ul>
  </div>

  <div class = "prepare_pr">
    <h2>Project Actived</h2>
    <ul class="projects root">
      <% Project.get_project_by_state(Settings.state.actived).each do |project| %>
        <li class="root">
          <div class="root">
            <%= link_to project.name, url_for(action: :show, id: project.id), class: "project my-project" %>
            <% if project.description.present? %>
              <div class="wiki description">
                <p><%= project.description %></p>
              </div>
            <% end %>
          </div>
        </li>
      <% end %>
    <ul>
  </div>

  <div class = "prepare_pr">
    <h2>Project Finished</h2>
    <ul class="projects root">
      <% Project.get_project_by_state(Settings.state.finished).each do |project| %>
        <li class="root">
          <div class="root">
            <%= link_to project.name, url_for(action: :show, id: project.id), class: "project my-project" %>
            <% if project.description.present? %>
              <div class="wiki description">
                <p><%= project.description %></p>
              </div>
            <% end %>
          </div>
        </li>
      <% end %>
    <ul>
  </div> 
  
</selection>

app/views/projects/show.html.erb
<selection id="project_show">
  <div class="ctsTit">
    <h2><%= h2_label %></h2>
    <nav>
      <%= link_to_if((@project.editable? && (current_user.projects.include? @project)),
          t(:cost, scope: [:views, :labels]), url_for(controller: :costs, action: :new, project_id: @project),
          class: "btn btn-small btn-warning") {} %>
    </nav>
  </div>
  <div class="splitcontentleft">
    <div class="issues box">
      <h3><%= @project.name %></h3>
      <p><%= @project.description %></p>

      <ul class = "circle">
        <li><%= model.human_attribute_name :start_date %>: <%= @project.start_date%></li>
        <li><%= model.human_attribute_name :due_date %>: <%= @project.due_date%></li>
        <li><%= model.human_attribute_name :end_date %>: <%= @project.end_date%></li>
      </ul>
    </div>
  </div>


  <div class="splitcontentright">
    <div class="members box">
      <div style= "width:76%;display: inline-block;"><h3>Members</h3></div>
      <div id = "edit_roles" style="display: inline-block;"><%= link_to t(:button_assign, scope: [:views, :labels]), project_project_users_path(@project.id) %></div>
      <% @project.project_users.each do |project_user| %>
            <div style="display: inline-block;">
              <%= link_to image_tag(project_user.user.avatar_url, class: "avatar", alt: "No image"),
                url_for(controller: :project_users, action: :edit, id: project_user.id), data: project_user.user.display_name %>
            </div>
      <% end %>
    </div>
  </div>
  <div class="form-actions">
    <%= link_to_if(current_user.is_manager?, t(:button_index, scope: [:views, :labels]),
        url_for(action: :index), class: "btn") {} %>
    <%= link_to_if(@project.editable? && current_user.is_manager?, t(:button_edit, scope: [:views, :labels]),
        url_for(action: :edit), class: "btn btn-primary") {} %>
    <%= link_to_if(@project.deletable? && current_user.is_manager?, t(:button_delete, scope: [:views, :labels]),
        url_for(action: :destroy), confirm: t(:delete_confirm, scope: [:views, :messages]), method: :delete,
        class: "btn btn-danger") {} %>
  </div>

</section>