config/routes.rb
HrSystem::Application.routes.draw do
  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  resources :reports do
    get :summary, on: :collection
  end
  resources :report_categories
  resources :vacation_types
  
  resources :stickies
  resources :users do
    get :get_team, on: :collection
    get :get_all_user, on: :collection
    get :profile, on: :member
    patch :update_profile, on: :member
    post :update_profile, on: :member
    post :update_user_role, on: :collection
    get :organizations, on: :collection
  end
  
  resources :groups do
    resources :teams
  end

  resources :project_users do
    resources :project_user_roles
  end

  resources :projects do
    resources :costs
    resources :project_users do
      get :member_list, on: :collection
      post :update_roles, on: :collection
    end
    get :gantt, on: :collection
    get :gantt_list, on: :collection
    get :export_excel, on: :collection
    post :assign_members, on: :collection
  end
  resources :project_users

  resources :payslips do
    get :download, on: :member
    post :send_payslip, on: :collection
  end

  resources :feedbacks do
    get :fixed, on: :member
  end

  resources :checkpoint_periods
  resources :questions
  resources :question_types do
    post :add_questions, on: :collection
    resources :question_type_relations
  end

  resources :checkpoints do
    get :review, on: :member
    get :ranking, on: :collection
  end

  resources :pickup_lists do
    post :assign_members, on: :collection
    resources :pickup_list_users, only: [:index, :destroy]
  end

  root to: "users#index"

end

app/models/feedback.rb
class Feedback < Base

  belongs_to :user

  state_machine :fixed, initial: :false do
    event :set_fixed do
      transition :false => :true
    end
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < BaseController
  def index
  end

  def create
    respond_to do |format|
      if @success = @feedback.save
        format.js
      else
        format.js
      end
    end
  end

  def destroy
    respond_to do |format|
      if @feedback.destroy
        format.html { redirect_to action: :index }
      else
        format { redirect_to action: :show }
      end
    end
  end

  def fixed
    feedback = Feedback.find(params[:id])
    feedback.set_fixed
    @id = params[:id]
    respond_to do |format|
      format.js
    end
  end

private
  def model_params
    params.require(:feedback).permit(:user_id, :title, :content) if params[:feedback]
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/create.js.erb
<% if @success %>
  $(".form_feedback").hide(500);
  $(".feedback_notice").delay(600).show(400);
  $(".feedback_notice").delay(2000).hide(300);
  $(".form_feedback .reset").val("");
<% end %>

app/views/feedbacks/fixed.js.erb
$("#feedback_<%= @id %>").siblings("i").show();
$("#feedback_<%= @id %>").remove();

app/views/feedbacks/index.html.erb
<selection>
  <table class="table_static">
    <tr>
      <th width="15%">Title</th>
      <th width="15%">Name</th>
      <th>Content</th>
      <th width="15%"></th>
    </tr>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.title %></td>
        <td><%= feedback.user.display_name %></td>
        <td><%= feedback.content %></td>
        <td>
        <div class="link">
          <i class="icon_tick icon" style="display: <%= feedback.fixed ? '' : 'none' %>"></i>
          <%= link_to_if(!feedback.fixed, "Fixed", fixed_feedback_path(feedback), remote: true, class: "btn btn-primary btn-mini", id: "feedback_#{feedback.id}") {} %>
          <%= link_to feedback_path(feedback), method: :delete, confirm: t(:confirm_delete, scope: [:views, :labels]) do %>
            <i class="icon_delete icon"></i>
          <% end %>
        </div>
        </td>
      </tr>
    <% end %>
  </table>
</selection>